# Site settings
title: Ross Mackay
email: ross@rossmackay.co
phone: 07805284648
description: "Ross Mackay"
baseurl: ""
url: "rossmackay.co"
twitter: r_mcky
github:  mcky

exclude: [node_modules, package.json, gulpfile.js, CNAME]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-redirect-from
