# Site settings
title: Ross Mackay
email: ross@rossmackay.co
description: "Site description."
baseurl: ""
url: "http://rossmackay.co"
twitter_username: r_mcky
github_username:  mcky

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Build settings
markdown: kramdown
permalink: pretty
